### ISSUE TITLE
목데이터에서 날짜를 지우기 보다 프론트 UI에서 가공하면 어떨까요?

### ISSUE THREAD

**Issue by ebchoi** [ebchoi/chart-and-board#7]
목데이터에서 날짜를 지우기 보다 프론트 UI에서 가공하면 어떨까요?
지난날은 날짜로 표시하고 당일 기준으로는 경과된 시간으로 표시하는 예시로 나와있어서 시간 값도 넣었던거라서요!

_Originally posted by @ebchoi in https://github.com/ebchoi/chart-and-board/pull/4#discussion_r998383440_

**Comment by sojae** [comment]
넵 수정했습니다
